version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: ./server/Dockerfile # Path to the backend Dockerfile
    working_dir: /server
    ports:
      - "5001:5001" # Expose the backend on port 5000
    volumes:
      - ./server:/server # Mount backend code to enable live reloading (optional)
    environment:
      - NODE_ENV=production
    depends_on:
      - mongo # Ensure the database starts before the backend

  frontend:
    build:
      context: .
      dockerfile: ./client/Dockerfile # Path to the frontend Dockerfile
    ports:
      - "3000:80" # Expose the React frontend (served via Nginx) on port 3000
    depends_on:
      - backend # Ensure the backend starts before the frontend

  mongo:
    image: mongo:latest  # Use the official MongoDB image
    ports:
      - "27017:27017"  # Expose MongoDB on port 27017
    volumes:
      - mongo-data:/data/db  # Persist MongoDB data using a Docker volume

volumes:
  mongo-data:
    driver: local
